MONGOALCHEMY_DATABASE = 'MONGOALCHEMY_DATABASE'
MONGOALCHEMY_CONNECTION_STRING = 'MONGOALCHEMY_CONNECTION_STRING'
SECRET_KEY = 'SECRET_KEY'


AUTHORIZATION = 'Authorization'
BEARER_REPLACE = 'Bearer '

PUBLIC_ID = 'public_id'
PASSWORD = 'password'
USERNAME = 'username'
EXP = 'exp'
TOKEN = 'token'
NAME = 'name'
BRAND_NAME = 'brandName'
