MONGOALCHEMY_DATABASE = 'MONGOALCHEMY_DATABASE'
MONGOALCHEMY_CONNECTION_STRING = 'MONGOALCHEMY_CONNECTION_STRING'
SECRET_KEY = 'SECRET_KEY'


AUTHORIZATION = 'Authorization'
BEARER_REPLACE = 'Bearer '

PUBLIC_ID = 'public_id'
PASSWORD = 'password'
USERNAME = 'username'
EXP = 'exp'
TOKEN = 'token'
NAME = 'name'
BRAND_NAME = 'brandName'
BRAND = 'brand'
ID = 'id'
IDS = 'ids'
ROWS = 'rows'
PAGE = 'page'
RESULTS = 'results'
COUNT = 'count'
TOTAL = 'total'
ROLE = 'permissions'
ADMIN = 'admin'
OPERATOR = 'operator'
COUNTRY = 'country'
YEAR = 'year'
CEO = 'ceo'
ENTRY = 'entry'
ISIN = 'isin'
SO = 'so'
WATER_PROOF = 'water_proof'
H5G = 'h5g'
RAM = 'ram'
ROWS_PER_PAGE = 5
